export const MAIL_LIST = {
    'qq.com': 'http://mail.qq.com',
    'gmail.com': 'http://mail.google.com',
    'sina.com': 'http://mail.sina.com.cn',
    '163.com': 'http://mail.163.com',
    '126.com': 'http://mail.126.com',
    'yeah.net': 'http://www.yeah.net/',
    'sohu.com': 'http://mail.sohu.com/',
    'tom.com': 'http://mail.tom.com/',
    '139.com': 'http://mail.10086.cn/',
    'hotmail.com': 'http://www.hotmail.com',
    'live.com': 'http://login.live.com/',
    'live.cn': 'http://login.live.com/',
    'live.com.cn': 'http://login.live.com/',
    '189.com': 'http://webmail16.189.cn/webmail/',
    'yahoo.com.cn': 'http://login.yahoo.com',
    'yahoo.cn': 'http://login.yahoo.com',
    'eyou.com': 'http://login.yahoo.com',
    '21cn.com': 'http://mail.21cn.com/',
    '188.com': 'http://www.188.com/',
    'foxmail.com': 'http://mail.qq.com/cgi-bin/loginpage?t=fox_loginpage',
    'sunmi.com': 'http://mail.sunmi.com/',
};
